---
  title: "About This Website"
  
---
  
The Española tortoise species, estimated to have lost 99% of its original population, is now thriving thanks to an extensive, 55-year effort by the Galapagos National Park to bring this species back from the brink of extinction. On March 15, 2020, one of the Galapagos National Park Directorate's  greatest conservation success stories in half a century comes to an end with the closing of the Española breeding program and return of the 15 original breeding tortoises back to their island of origin, on which more than 2,000 of their offspring now thrive. With these tortoises' help, the island’s ecosystem will continue to recover after over 200 years without a thriving tortoise population and 100 years of goat occupation. 

This app enables you to track each of the 15 Espanola tortoises (12 females and 3 males) as they explore their home island, back again after more than 50 years away.  Their locations recorded on small GPS tags on the carapace of each torotise are reported daily via satellite for reporting here.

Undertaken by: 
Giant Tortoise Restoration Initiative, a collaborative 15-year project (2014-2028) implemented by the Galapagos National Park Directorate and the Galapagos Conservancy with support from visiting scientists from around the world.

GTRI: https://www.galapagos.org/conservation/our-work/tortoise-restoration/

DPNG: https://www.galapagos.gob.ec/en/national-park/

GC: https://www.galapagos.org/

Website by Hamish Gibbs. To report an issue with this site, create an [issue](https://github.com/hamishgibbs/espanola_tortoise_release/issues/new).

