---
---

```{css echo=FALSE}
#language-active{
  display: block;
}

#language-inactive{
  display: none;
}

.sub-header-list {
  list-style-type: none;
  margin: 0;
  padding: 0;
  overflow: hidden;
}

.sub-header-list-item {
  float: left;
}

.sub-header-list-item:last-child { float:right; }

```

<div style="display: table; margin: 0 auto; width: 100%">
  <ul class="sub-header-list" style="width: 100%; margin: 0; padding: 0;">
    <li class="sub-header-list-item" list-style-type="none" style="display: inline;">
      <h2 class="alt-language-text" id="language-active">The tortoises</h2>
      <h2 class="alt-language-text" id="language-inactive">Las tortugas</h2>
    </li>
    <li class="sub-header-list-item" list-style-type="none" style="display: inline;">
      <button id="languageToggleButton" onclick="toggleLanguage()" style="margin-top: 25px;">Español</button>
    </li>
  </ul>
</div>

```{js echo=FALSE}
toggleLanguage = function(){
  
  var language_elements = document.querySelectorAll(".alt-language-text")
  
  var i;
  for (i = 0; i < language_elements.length; i++) {
    
    if(language_elements[i].getAttribute('id') == 'language-active'){
      language_elements[i].setAttribute('id', 'language-inactive')
    }else{
      language_elements[i].setAttribute('id', 'language-active')
    }
  
  }
  
  current_text_button = document.getElementById('languageToggleButton').innerText
  
  if(current_text_button == "Español"){
    document.getElementById('languageToggleButton').innerText = "English"
  }else{
    document.getElementById('languageToggleButton').innerText = "Español"
  }
}

```

```{r echo = F}
suppressPackageStartupMessages({
  require(plotly)
})
```

```{r echo = F, warning = FALSE}
line_sum <- read_rds('processed_data/length_summary.rds') %>% 
  dplyr::arrange(length) %>% 
  mutate(id = factor(id, levels = id))

tpal <- colorFactor(viridis::viridis(15), lines$id)

plot_ly(line_sum, x = ~length, y = ~id, type = 'bar', orientation = 'h',
        marker = list(color = ~tpal(line_sum$id))) %>% 
  layout(xaxis = list(title = "Distance travelled - Distancia recorrida (km)"),
         yaxis = list(title=''))

```